version: "3"

services:
  apache-php74:
    build: build/apache-php74/
    ports:
      - "8074:80"
    restart: always
    volumes:
      - ./volumes/apache-php74:/etc/apache2/sites-enabled
      - ~/Desarrollo:/var/www/html

  apache-php80:
    build: build/apache-php80/
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./volumes/apache-php80:/etc/apache2/sites-enabled
      - ~/Desarrollo:/var/www/html

  apache-php81:
    build: build/apache-php81/
    ports:
      - "8081:80"
    restart: always
    volumes:
      - ./volumes/apache-php81:/etc/apache2/sites-enabled
      - ~/Desarrollo:/var/www/html

  database:
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    restart: always
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - database

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always
