version: "3"

services:
  apache-php8:
    build: apache-php8/
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./volumes/apache-php8:/etc/apache2/sites-enabled
      - ~/Desarrollo:/var/www/html

  apache-php7:
    build: apache-php7/
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./volumes/apache-php7:/etc/apache2/sites-enabled
      - ~/Desarrollo:/var/www/html

  database:
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    restart: always
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - database
