version: "3"

services:
  web:
    build: apache/
    ports:
      - "80:80"
    restart: always
    volumes:
      - ~/Desarrollo:/var/www/html
      - ~/Apps/Docker/containers/lampp-apache/conf:/etc/apache2/sites-enabled

  web-legacy:
    build: apache-legacy/
    ports:
      - "8056:80"
    restart: always
    volumes:
      - ~/Desarrollo:/var/www/html
      - ~/Apps/Docker/containers/lampp-apache-legacy/conf:/etc/apache2/sites-enabled

  database:
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ~/Apps/Docker/containers/lampp-mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8090:80"
    restart: always
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - database
